---
name: CD
on:
  workflow_call:
    secrets:
      CICD_APP_ID:
        required: true
      CICD_PRIVATE_KEY:
        required: true
jobs:
  release:
    name: Release
    uses: ./.github/workflows/release.yaml
    permissions:
      attestations: write
      id-token: write
    secrets:
      CICD_APP_ID: ${{ secrets.CICD_APP_ID }}
      CICD_PRIVATE_KEY: ${{ secrets.CICD_PRIVATE_KEY }}
