name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: 
          - ubuntu-latest
          - macos-13 # Intel
          - macos-latest # ARM
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          # TODO(ttlgcc): Parameterize flake version.
          nix_archives_url: https://github.com/fabrictest/lix-quick-install-action/releases/download/v1
          lix_version: 2.91.1
      - uses: cachix/cachix-action@v15
        with:
          name: fabrictest
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build Lix archives
        id: build-lix-archives
        run: |
          nix build .#lix-archives
          echo "result=$(readlink result)" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v4
        with:
          name: lix-archives-${{ runner.os }}-${{ runner.arch }}
          path: ${{ steps.build-lix-archives.outputs.result }}/

  test:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # Intel
          - macos-latest # ARM
        lix_version:
          - 2.91.1
          - 2.90.0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        id: lix-archives
        with:
          name: lix-archives-${{ runner.os }}-${{ runner.arch }}
      - uses: ./
        with:
          nix_archives_url: file://${{steps.lix-archives.outputs.download-path}}
          lix_version: ${{ matrix.lix_version }}
          nix_on_tmpfs: true
      - name: Test nix
        run: nix-build -v --version
      - name: Add to store
        run: |
          file="$RANDOM"
          echo "$RANDOM" > "$file"
          path="$(nix-store --add "./$file")"

  test-cachix:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # Intel
          - macos-latest # ARM
        lix_version:
          - 2.90.0
          - 2.91.1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        id: lix-archives
        with:
          name: lix-archives-${{ runner.os }}-${{ runner.arch }}
      - uses: ./
        with:
          nix_archives_url: file://${{ steps.lix-archives.outputs.download-path }}
          lix_version: ${{ matrix.lix_version }}
          nix_conf: ${{ matrix.nix_conf }}
      - uses: cachix/cachix-action@v15
        with:
          name: fabrictest
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Verify nix config
        run: |
          if ! egrep -q "^substituters = https://cache.nixos.org https://fabrictest.cachix.org$" "$HOME/.config/nix/nix.conf"; then
            echo "Invalid substituters config"
            exit 1
          fi
      - name: Push to Cachix
        if: github.event_name == 'push' && github.repository_owner == 'fabrictest'
        run: |
          dd if=/dev/urandom of=random count=1
          cachix push fabrictest "$(nix add-to-store random)"

  release:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
      - test-cachix
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: lix-archives-Linux-X64
          path: /tmp/archives
      - uses: actions/download-artifact@v4
        with:
          name: lix-archives-macOS-X64
          path: /tmp/archives
      - uses: actions/download-artifact@v4
        with:
          name: lix-archives-macOS-ARM64
          path: /tmp/archives
      - uses: ./
        with:
          nix_archives_url: file:///tmp/archives
          lix_version: 2.91.1
      - uses: cachix/cachix-action@v15
        with:
          name: fabrictest
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build release script
        run: nix build .#release
      - name: Release if needed
        run: ./result/bin/release /tmp/archives ./RELEASE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
