---
name: CICD
on:
  pull_request:
  push:
    branches:
      - main
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  # renovate: datasource=github-runners depName=macos
  RUNNER_MACOS_VERSION: "15"
  # renovate: datasource=github-runners depName=ubuntu
  RUNNER_UBUNTU_VERSION: "24.04"
jobs:
  resolve:
    name: Resolve
    runs-on: ubuntu-latest
    steps:
      - name: Runners to use
        id: runner-os
        shell: bash
        run: |
          cat >>"$GITHUB_OUTPUT" <<EOF
          json<<JSON
          [
            "macos-$RUNNER_MACOS_VERSION",
            "macos-13",
            "ubuntu-$RUNNER_UBUNTU_VERSION"
          ]
          JSON
          EOF
    outputs:
      runner-os: ${{ steps.runner-os.outputs.json }}
  build:
    name: Build
    needs:
      - resolve
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJSON(needs.resolve.outputs.runner-os) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2
      - name: Which version should I use to bootstrap Lix?
        id: bootstrap-version
        shell: bash
        run: |
          git switch --detach HEAD~1
          cat >>"$GITHUB_OUTPUT" <<EOF
          string=$(tr -d \\n version.txt)
          EOF
          git switch -
      - name: Bootstrap Lix
        uses: ./
        with:
          archives-url: https://github.com/fabrictest/lix-quick-install-action/releases/download/v${{ step.bootstrap-version.outputs.string }}
      - name: Set up Cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: ${{ vars.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Build archives
        id: archives
        shell: bash
        run: |
          nix build .#lix-archives
          cat >>"$GITHUB_OUTPUT" <<EOF
          result=$(readlink result)
          EOF
      - name: Upload archives to GitHub
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: archives-${{ runner.os }}-${{ runner.arch }}
          path: ${{ steps.archives.outputs.result }}/
  test:
    name: Test
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJSON(needs.resolve.outputs.runner-os) }}
        lix-version:
          - 2.90.0
          - 2.91.1
    needs:
      - build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Download archives from GitHub
        id: archives
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: archives-${{ runner.os }}-${{ runner.arch }}
      - name: Install Lix ${{ matrix.lix-version }}
        uses: ./
        with:
          lix-version: ${{ matrix.lix-version }}
          lix-on-tmpfs: true
          archives-url: file://${{ steps.archives.outputs.download-path }}
      - name: Set up Cachix
        if: ${{ github.event_name == 'push' && github.repository_owner == 'fabrictest' }}
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: ${{ vars.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_TOKEN }}
          skipPush: true
      - name: Verify that Lix was installed
        shell: bash
        run: |
          nix-build -v --version
      - name: Verify that one can add a file to the Lix store
        id: lix-store-add
        shell: bash
        run: |
          f=./$RANDOM
          echo $RANDOM >$f
          cat >>"$GITHUB_OUTPUT" <<EOF
          result=$(nix-store --add $f)
          EOF
      - name: Verify that one can push such file to Cachix
        if: ${{ github.event_name == 'push' && github.repository_owner == 'fabrictest' }}
        shell: bash
        run: |
          cachix push "$cache" "$result"
        env:
          cache: ${{ vars.CACHIX_NAME }}
          result: ${{ steps.lix-store-add.outputs.result }}
  release:
    name: Release
    needs:
      - test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}
    steps:
      - name: Generate ephemeral GitHub token
        id: app-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Set M.S.B.O.Y. as Git author and committer
        shell: bash
        run: |
          bot_email="$(gh api "/users/$bot_name" --jq .id)+$bot_name@noreply.users.github.com"
          cat >>"$GITHUB_ENV" <<EOF
          GIT_AUTHOR_NAME=$bot_name
          GIT_AUTHOR_EMAIL=$bot_email
          GIT_COMMITTER_NAME=$bot_name
          GIT_COMMITTER_EMAIL=$bot_email
          EOF
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          bot_name: ${{ steps.app-token.outputs.app-slug }}[bot]
      - name: Cut release
        id: release
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          target-branch: ${{ github.ref_name }}
      - name: Check out repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        shell: bash
        run: |
          for tag in "v$M" "v$M.$m"; do
            git tag -d "$tag" ${{ runner.debug && '' || '>/dev/null 2>&1' }} || :
            git push origin :"$tag" ${{ runner.debug && '' || '>/dev/null 2>&1' }} || :
            git tag -a "$tag" -m "Release $tag"
            git push origin "$tag"
          done
        env:
          M: ${{ steps.release.outputs.major }}
          m: ${{ steps.release.outputs.minor }}
    outputs:
      created: ${{ steps.release.outputs.release_created || '' }}
      tag: ${{ steps.release.outputs.tag_name }}
  publish:
    name: Publish
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJSON(needs.resolve.outputs.runner-os) }}
    runs-on: ${{ matrix.os }}
    needs:
      - release
    if: ${{ needs.release.outputs.created }}
    permissions:
      id-token: write
    steps:
      - name: Generate ephemeral GitHub token
        id: app-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Download archives
        id: archives
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: archives-${{ runner.os }}-${{ runner.arch }}
      - name: Attest archives
        uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          subject-path: ${{ steps.archives.outputs.download-path }}/lix-*.tar.zstd
      - name: Attach archives to the GitHub release
        shell: bash
        run: |
          gh release upload "$tag" "$archives"/lix-*.tar.zstd
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          tag: ${{ needs.release.outputs.tag }}
          archives: ${{ steps.archives.outputs.download-path }}
