name: CICD
on:
  pull_request:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        os: 
          - ubuntu-latest
          - macos-13 # X64
          - macos-latest # ARM64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Bootstrap Lix
        uses: ./
        with:
          # TODO(ttlgcc): Parameterize flake version.
          lix-archives-url: https://github.com/fabrictest/lix-quick-install-action/releases/download/v6
      - name: Set up Cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build archives
        id: lix-archives
        shell: bash
        run: |
          nix build .#lix-archives
          cat >>"$GITHUB_OUTPUT" <<EOF
          result=$(readlink result)
          EOF
      - name: Upload archives
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: lix-archives-${{ runner.os }}-${{ runner.arch }}
          path: ${{ steps.lix-archives.outputs.result }}/
  test:
    name: Test
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # X64
          - macos-latest # ARM64
        lix-version:
          - 2.90.0
          - 2.91.1
    needs:
      - build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Download archives
        id: lix-archives
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: lix-archives-${{ runner.os }}-${{ runner.arch }}
      - name: Install Lix ${{ matrix.lix-version }}
        uses: ./
        with:
          lix-version: ${{ matrix.lix-version }}
          lix-archives-url: file://${{ steps.lix-archives.outputs.download-path }}
          lix-on-tmpfs: true
      - name: Set up Cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Verify that Lix was installed
        shell: bash
        run: |
          nix-build -v --version
      - name: Verify that one can add a file to the Lix store
        id: lix-store-add
        shell: bash
        run: |
          f=./$RANDOM
          echo $RANDOM >$f
          cat >>"$GITHUB_OUTPUT" <<EOF
          result=$(nix-store --add $f)
          EOF
      - name: Verify that one can push such file to Cachix
        if: ${{ github.event_name == 'push' && github.repository_owner == 'fabrictest' }}
        shell: bash
        run: |
          cachix push "${{ vars.CACHIX_CACHE_NAME }}" "${{ steps.lix-store-add.outputs.result }}"
  release:
    name: Release
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Download Lix archive (Linux, X64)
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: lix-archives-Linux-X64
          path: /tmp/archives
      - name: Download Lix archive (macOS, X64)
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: lix-archives-macOS-X64
          path: /tmp/archives
      - name: Download Lix archive (macOS, ARM64)
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: lix-archives-macOS-ARM64
          path: /tmp/archives
      - name: Install Lix
        uses: ./
        with:
          lix-archives-url: file:///tmp/archives
      - name: Set up Cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build release script
        run: nix build .#release
      - name: Release if needed
        run: ./result/bin/release /tmp/archives ./RELEASE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
