name: Examples
on:
  push:
    branches:
      - master
jobs:
  minimal:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # X64
          - macos-latest # ARM64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fabrictest/lix-quick-install-action@v4
      - run: nix-build --version
  flakes:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # X64
          - macos-latest # ARM64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: fabrictest/lix-quick-install-action@v4
      - name: nix build
        run: nix build ./examples/flakes
      - name: hello
        run: ./result/bin/hello
