---
name: Examples
on:
  push:
    branches:
      - master
jobs:
  flakes:
    name: Flakes
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # X64
          - macos-latest # ARM64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Lix
        uses: fabrictest/lix-quick-install-action@v7.0.2
      - name: Print Lix version
        run: nix-build --version
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build flake
        run: nix build ./examples/flakes
      - name: Print `hello, world` message
        run: ./result/bin/hello
