name: Examples
on:
  push:
    branches:
      - master
jobs:
  minimal:
    name: Minimal
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # X64
          - macos-latest # ARM64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Lix
        uses: fabrictest/lix-quick-install-action@v4
      - name: Retrieve Lix version
        run: nix-build --version
  flakes:
    name: Flakes
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # X64
          - macos-latest # ARM64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fabrictest/lix-quick-install-action@v4
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build flake
        run: nix build ./examples/flakes
      - name: Call `hello`
        run: ./result/bin/hello
