---
name: Release
on:
  workflow_call:
    outputs:
      tag:
        description: |
          The name of the released tag, or `''` if there was no release.

          Example: `v1.2.3`.
        value: ${{ jobs.cut.outputs.tag }}
    secrets:
      CICD_APP_ID:
        description: |
          TODO(ttlgcc): Write secret description.
        required: true
      CICD_PRIVATE_KEY:
        description: |
          TODO(ttlgcc): Write secret description.
        required: true
jobs:
  cut:
    name: "?"
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.cut.outputs.release_created && steps.cut.outputs.tag_name || '' }}
    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        with:
          app-id: ${{ secrets.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_PRIVATE_KEY }}
      - name: Cut release
        id: cut
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          target-branch: ${{ github.ref_name }}
